# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: Terraform plan
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure subscription 1(7bd61c18-776a-415c-be12-5cf9e3cf04d7)'
    allowTelemetryCollection: false
    
- task: TerraformCLI@0
  displayName: Terraform apply
  inputs:
    command: 'apply'
    environmentServiceName: 'Azure subscription 1(7bd61c18-776a-415c-be12-5cf9e3cf04d7)'
    commandOptions: '--auto-approve'
    allowTelemetryCollection: true