name: Build and deploy an app to AKS

on:
  # push:
  #   branches:
  #   - main
  pull_request:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Az AKS login
      run: |



    - uses: actions/checkout@v1
    - name: K8s Configuration
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
        kubectl get pods -A

    - uses: actions/checkout@v1
    - name: Deployment
      run: |
        cd ./app
        kubectl apply -f php.yaml
        sleep 30 
        kubectl get svc  | grep web

