name: PHP

on:
  push:
   branches:
     - main 
   tags:
     - v1
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd ./app/php
        echo "${{ secrets.DOCKERPW }}" | docker login -u "aarafat56" --password-stdin
        docker image build -t aarafat56/php:latest .
        docker push aarafat56/php:latest


    - uses: actions/checkout@v1
    - name: Az AKS login
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --service-principal -u c909cd46-24c4-46ba-b9dc-854427f9ca6e -p MU68Q~98u4NAwZLcT6mqFj5vQAhDg0g45QZF_cH0 --tenant fc5c3a8c-573c-4f49-900e-65ee41a973d5
        az account set --subscription 7bd61c18-776a-415c-be12-5cf9e3cf04d7
        az aks get-credentials --resource-group test-arafat-rg --name arafat-aks-cluster
        az account set --subscription 7bd61c18-776a-415c-be12-5cf9e3cf04d7


    - uses: actions/checkout@v1
    - name: Deploy
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
        kubectl get pods -A

