name: 'Terraform'

on:
  pull_request:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Az AKS login
      run: |



    - uses: actions/checkout@v1
    - name: Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        terraform init 
        terraform plan

