name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Az AKS login
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --service-principal -u 6d12c134-bca2-45fe-8432-79ff7bbb627c -p gTe8Q~5E12XbJybuiESTu8PrqPjWDJOg_3NM5ajl --tenant fc5c3a8c-573c-4f49-900e-65ee41a973d5
        # az account set --subscription 7bd61c18-776a-415c-be12-5cf9e3cf04d7
        # az aks get-credentials --resource-group test-arafat-rg --name arafat-aks-cluster
        az account set --subscription 7bd61c18-776a-415c-be12-5cf9e3cf04d7


    - uses: actions/checkout@v1
    - name: Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        terraform init 
        terraform plan

